# https://chatgpt.com/g/g-FMjktwiXn-gitops/c/675db476-be2c-800b-8b19-2eddebf9c528
name: Events Demo 1

on:
  push:
    branches:
      - main
  issues:
    types: 
      - opened
      - edited
      - closed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3



      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: install node lint
        run: npm lint
  
      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Test code
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: Build code
        run: npm run build
        
      
  # Job 4: Log Issue Event Data
  log-issue-event:
    name: Log Issue Event Data
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'  # Run this job only for 'issues' events
    steps:
      - name: Output issue event details
        run: echo "${{ toJSON(github.event) }}" 
  
  # successful-job:
  #   name: successful push
  #   runs-on: ubuntu-latest
  #   if: *mina tre förgående jobb lyckas så vill jag sätta ihop hela köret, lint, test, build, till en deploy*
  
  # - name: Simulate Deployment
  #   run: echo "Deploying..."    