# https://chatgpt.com/g/g-FMjktwiXn-gitops/c/675db476-be2c-800b-8b19-2eddebf9c528
name: Events Demo 1

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v3

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: run linting
        run: npm run lint

  test:
    runs-on:
      ubuntu-latest
    steps:
    - name: checkout repo code
      uses: actions/checkout@v3
    
    - name: set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: test code
      run: npm run test
      

  build:
    runs-on:
      ubuntu-latest
    steps:
    - name: checkout repo code
      uses: actions/checkout@v3
    
    - name: set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Build code
      run: npm run build
        
      
    



deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Output event data
          run: echo "${{ toJSON(github.event) }}"

          
        - name: Deploy project
          run: echo "Deploying..."